apiVersion: v1
kind: Pod
metadata:
  name: animalese
  labels:
    name: animalese
spec:
  containers:
  - name: animalese
    image: us.gcr.io/primordial-gate-277004/animalese:latest
    command: ["sleep"]
    args: ["3h"]
    resources:
      requests:
        memory: "1.5Gi"
        cpu: "2"
      limits:
        memory: "1.5Gi"
        cpu: "2"